\hypertarget{class_socket_exception}{}\section{Socket\+Exception Class Reference}
\label{class_socket_exception}\index{Socket\+Exception@{Socket\+Exception}}


{\ttfamily \#include $<$Socket\+Exception.\+h$>$}

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
{\bfseries Socket\+Exception} (std\+::string s)\hypertarget{class_socket_exception_a09ddb0c061c40fcb527ff89a2e803342}{}\label{class_socket_exception_a09ddb0c061c40fcb527ff89a2e803342}

\item 
std\+::string {\bfseries description} ()\hypertarget{class_socket_exception_ad7920caebddc99b6bbb7dbede569fa18}{}\label{class_socket_exception_ad7920caebddc99b6bbb7dbede569fa18}

\end{DoxyCompactItemize}


\subsection{Detailed Description}
A \hyperlink{class_socket_exception}{Socket\+Exception} is thrown whenever issues occur with socket connections. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/\+Users/\+Dat/\+Clion\+Projects/saas/lib/network/inc/Socket\+Exception.\+h\end{DoxyCompactItemize}
